name: Generate and Transmit SBOM

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    # Basic setup for Python
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - uses: anchore/sbom-action@v0
        with:
          path: .
          output-file: ./bom.json
          artifact-name: bom.json
          format: cyclonedx-json
      # Transmit a copy of our generated SBOM to Manifest
      - name: Transmit generated SBOM to Manifest
        uses: manifest-cyber/manifest-github-action@main
        id: transmit
        with:
          # Generate an API key at https://app.manifestcyber.com/organization
          # Store the key as a secret in Github, and reference it below
          # Do not share this key - this allows the holder to upload SBOM's to Manifest on your behalf
          apiKey: ${{ secrets.MANIFEST_API_KEY }}
          bomFilePath: "./bom.json"
          sbom-version: ""
          sbom-name: testing-for-name
          sbom-output: cyclonedx-json
